# Generated by Django 4.2.16 on 2025-02-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0008_alter_resume_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
