# Generated by Django 5.1.1 on 2024-10-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
