# Generated by Django 5.1.1 on 2024-10-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0002_joblisting_company_url_joblisting_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='company_url',
        ),
    ]
