# Generated by Django 5.1.1 on 2024-10-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0003_remove_joblisting_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_link',
            field=models.URLField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
