# Generated by Django 5.1.1 on 2024-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0005_remove_joblisting_company_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='attributes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
