# Generated by Django 5.1.1 on 2024-10-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0004_joblisting_company_joblisting_company_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='company_link',
        ),
    ]
