# Generated by Django 5.1.1 on 2024-10-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0006_joblisting_attributes_alter_joblisting_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='salary',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='attributes',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
