# Generated by Django 5.1.1 on 2024-11-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0007_alter_resume_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='document',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
