# Generated by Django 5.1.1 on 2024-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0007_remove_joblisting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='benefits',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='attributes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
