# Generated by Django 5.1.1 on 2024-10-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0009_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='keywords',
            field=models.ManyToManyField(related_name='job_listings', to='scrape_jobs.keyword'),
        ),
        migrations.CreateModel(
            name='ResumeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='N/A')),
                ('keywords', models.ManyToManyField(related_name='resume_listings', to='scrape_jobs.keyword')),
            ],
        ),
    ]
