# Generated by Django 5.1.1 on 2024-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0012_remove_joblisting_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('In Progress', 'In Progress'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], max_length=50)),
                ('site', models.URLField(blank=True, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('In Person', 'In Person')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('interview_dates', models.JSONField(default=list)),
            ],
        ),
    ]
