# Generated by Django 5.1.1 on 2024-11-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0013_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_dates',
            field=models.JSONField(default=list, null=True),
        ),
    ]
